### ISSUE TITLE
cannot launch server

### ISSUE THREAD

**Issue by xuehy** [mhauskn/rcssserver#5]
` /home/xuehy/miniconda3/lib/python3.6/site-packages/hfo_py/bin/HFO --headless --frames-per-trial 500 --untouched-time 100 --offense-agents 1 --defense-agents 0 --offense-npcs 0 --defense-npcs 0 --port 6000 --offense-on-ball 0 --seed -1 --ball-x-min 0.000000 --ball-x-max 0.200000 --log-dir log --fullstate --no-logging`

```
[start.py] Cleaning up server and other processes
Traceback (most recent call last):
  File "/home/xuehy/miniconda3/lib/python3.6/site-packages/hfo_py/bin/HFO", line 198, in <module>
    main(parseArgs())
  File "/home/xuehy/miniconda3/lib/python3.6/site-packages/hfo_py/bin/HFO", line 81, in main
    %(serverCommand + serverOptions)
AssertionError: [start.py] Failed to launch Server with command: "/home/xuehy/miniconda3/lib/python3.6/site-packages/hfo_py/bin/rcssserver server::port=6000 server::coach_port=6001 server::olcoach_port=6002 server::coach=1 server::game_logging=0 server::text_logging=0 server::hfo_logging=0 server::hfo_log_dir=log server::game_log_dir=log server::text_log_dir=log server::synch_mode=1 server::hfo=1 server::fullstate_l=1 server::fullstate_r=1 server::coach_w_referee=1 server::hfo_max_trial_time=500 server::hfo_max_trials=-1 server::hfo_max_frames=-1 server::hfo_offense_on_ball=0 server::random_seed=-1 server::hfo_max_untouched_time=100 server::hfo_min_ball_pos_x=0.000000 server::hfo_max_ball_pos_x=0.200000 server::say_msg_size=1000 server::record_messages=0"

Another rcssserver may be running on the same port?
Try: "killall -9 rcssserver"
```

I am sure port 6000 - 6002 are not in use. What is wrong?

**Comment by mhauskn** [comment]
The most common issue I've seen is that there could be an rcssserver process still alive. Hence the "killall -9 rcssserver" to make sure there are no other rcssserver processes running. Beyond that, try directly executing the server command and see if you get a more informative error:

/home/xuehy/miniconda3/lib/python3.6/site-packages/hfo_py/bin/rcssserver server::port=6000 server::coach_port=6001 server::olcoach_port=6002 server::coach=1 server::game_logging=0 server::text_logging=0 server::hfo_logging=0 server::hfo_log_dir=log server::game_log_dir=log server::text_log_dir=log server::synch_mode=1 server::hfo=1 server::fullstate_l=1 server::fullstate_r=1 server::coach_w_referee=1 server::hfo_max_trial_time=500 server::hfo_max_trials=-1 server::hfo_max_frames=-1 server::hfo_offense_on_ball=0 server::random_seed=-1 server::hfo_max_untouched_time=100 server::hfo_min_ball_pos_x=0.000000 server::hfo_max_ball_pos_x=0.200000 server::say_msg_size=1000 server::record_messages=0

**Comment by xuehy** [comment]
There is no other rcssserver alive.  "killall -9 rcssserver" returns "rcssserver: no process found". Executing the server command leads to segmentation fault.

**Comment by mhauskn** [comment]
Very interesting. What OS are you using? What process did you use to install HFO? Were there errors during install?

**Comment by vbhatt-cs** [comment]
I was getting the same error when I run HFO. I installed it using the steps given in https://github.com/LARG/HFO on Ubuntu 16.04. Installation was fine but when I ran passing agents demo, I got similar output even though the ports were open and there was no rcssserver process running. Running only the rcssserver gave segmentation fault.

I tried installing rcssserver from this repo with following commands

````
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
make
sudo make install
````

and the server starts correctly. If I then modify <HFO>/bin/HFO to use this installation of rcssserver, I am able to run HFO without any errors.
